### PR TITLE
bitcoin_hashes >= 0.12, <= 0.13

### PR DESCRIPTION
**Pull request by kayabaNerve**

### CODE REVIEW

**Comment by tcharding** [comment]
Thanks for the contribution! I'm not the guy who merges things in this crate but if I was I'd want some sort of commit log and/or PR description for this. Its a breaking change and an unusual versioning style.

**Comment by tcharding** [comment]
Oh no worries, my bad.

**Comment by kayabaNerve** [comment]
@stevenroose Would you be willing to merge this and release 2.1.0? Is there some blocker I can work on?

**Comment by darosior** [comment]
Just stumbled upon this. Bumping `bitcoin_hashes` in this crate would help me to avoid a duplicate `bitcoin_hashes` in `liana`'s dependency:
```
$ cargo tree -d
bitcoin_hashes v0.11.0
└── bip39 v2.0.0
    └── liana v4.0.0 (/home/darosior/projects/wizardsardine/liana)

bitcoin_hashes v0.12.0
├── bitcoin v0.30.2
│   └── miniscript v10.0.0
│       └── liana v4.0.0 (/home/darosior/projects/wizardsardine/liana)
└── secp256k1 v0.27.0
    └── bitcoin v0.30.2 (*)
```

cc @stevenroose.

**Comment by stevenroose** [comment]
I prefer `<0.14` over `<=0.13`, so that I'm sure we have bumpes to 0.13 included.

**Comment by stevenroose** [comment]
> I prefer `<0.14` over `<=0.13`, so that I'm sure we have bumpes to 0.13 included.

Did this in 7f554391aef118f3ddb654cfafa7c45b91a2cd94.

**Pull request merged**
