### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by ayrat555**
- fix clippy warnings

### CODE REVIEW

**Comment by ayrat555** [comment]
@apoelstra @stevenroose hey. can you please review this pr?

the main change in this pr is `add_words` function. currently there is no way to get a list of words

**Comment by tcharding** [comment]
@apoelstra isn't involved in this crate, Steven is out of action right now, I can take a look for you though :)

**Comment by tcharding** [comment]
Can you put the clippy fixes in a separate commit please and the "add words" stuff in a commit on its own. Will make it much easier to review since I'm not super familiar with this code. FYI don't hold your breath for this to get merged any time soon, movement on this crate is a bit slow at the moment I'm afraid. We are doing our best :)

**Comment by ayrat555** [comment]
@tcharding done!

**Review by tcharding — COMMENTED** [review]
Woops, somehow when I did the original review these two comments didn't get posted. The rest looks good to me.

**Comment by tcharding** [comment]
If you remove the edition 2021 change and the toolchain version the its good to go!

**Comment by tcharding** [comment]
Can you squash the last commit please? That way there are no changes later in the series of patches that change something in an earlier patch. Makes review easier for the next guy. Thanks

**Comment by tcharding** [comment]
You'll need to amend the PR description too :)

**Comment by ayrat555** [comment]
@tcharding addressed your comments.

 if Steven is out of action, maybe he can give the ownership to someone else?

**Comment by tcharding** [comment]
Nah, we'll wait for him. Its open source, you can always fork it if you want to go a different direction.

**Comment by stevenroose** [comment]
The versioning part of this is handled in another MR and the `all_words` function seems to be identical to `.language().word_list()`, when `word_list` will be exposed in v1.1.0, see https://github.com/rust-bitcoin/rust-bip39/pull/40.

**Comment by ayrat555** [comment]
@stevenroose I removed this funciton

**Comment by tcharding** [comment]
This PR is only clippy changes now, perhaps https://github.com/rust-bitcoin/rust-bip39/pull/27 is better for that. @ayrat555 can you close if you are ok with waiting for #27 to go in?

**Comment by stevenroose** [comment]
Everything in this MR merged in some form or another except #27 indeed. Closing.

**Pull request closed without merging**
