### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by stevenroose**
I added in one change that I had pending, I can split that up if people don't like it.

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
Looks good to me, ACK 741698655f661c1f08bc36850e469e099369f605

**Comment by stevenroose** [comment]
Gonna await another ack.

**Comment by stevenroose** [comment]
Gonna await another ack. @jeandudey  maybe?

**Comment by benma** [comment]
Please also bump the bitcoin-hashes version to align with the one published by rust-bitcoin, which is currently bitcoin-hashes=0.12.0. This way if one uses both crates, the hashes dependency is not duplicated.

**Comment by jeandudey** [comment]
@benma Maybe three versions could be released to keep everyone happy as I need `bitcoin_hashes` to be 0.13 as `bitcoin_hashes` takes a lot of flash space due to unrolling of the implementations.

E.g.:

2.1.0 with bitcoin_hashes@0.11
2.2.0 with bitcoin_hashes@0.12
2.3.0 with bitcoin_hashes@0.13

**Comment by tcharding** [comment]
If no one needs 0.11 then we can use a range dependency over 12 and 13
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 2970cc5..2e57a82 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -48,13 +48,13 @@ serde = { version = "1.0", default-features = false, features = [ "alloc" ], opt
 zeroize = { version = "1.5", features = ["zeroize_derive"], optional = true }
 
 # Unexported dependnecies
-bitcoin_hashes = { version = "0.11.0", default-features = false }
+bitcoin_hashes = { version = ">=0.12.0, <0.13", default-features = false }
 unicode-normalization = { version = "=0.1.22", optional = true }
 
 [dev-dependencies]
 # Enabling the "rand" feature by default to run the benches
 bip39 = { path = ".", features = ["rand"] }
-bitcoin_hashes = "0.11.0" # enable default features for test
+bitcoin_hashes = "0.13" # enable default features for test
 
 
 [package.metadata.docs.rs]
diff --git a/src/pbkdf2.rs b/src/pbkdf2.rs
index e7d3375..326ca55 100644
--- a/src/pbkdf2.rs
+++ b/src/pbkdf2.rs
@@ -112,7 +112,7 @@ pub(crate) fn pbkdf2<M>(mnemonic: M, unprefixed_salt: &[u8], c: usize, res: &mut
                        prfc.input(unprefixed_salt);
                        prfc.input(&u32_to_array_be((i + 1) as u32));
 
-                       let salt = hmac::Hmac::from_engine(prfc).into_inner();
+                       let salt = hmac::Hmac::from_engine(prfc).to_byte_array();
                        xor(chunk, &salt);
                        salt
                };
@@ -120,7 +120,7 @@ pub(crate) fn pbkdf2<M>(mnemonic: M, unprefixed_salt: &[u8], c: usize, res: &mut
                for _ in 1..c {
                        let mut prfc = prf.clone();
                        prfc.input(&salt);
-                       salt = hmac::Hmac::from_engine(prfc).into_inner();
+                       salt = hmac::Hmac::from_engine(prfc).to_byte_array();
 
                        xor(chunk, &salt);
```

**Comment by tcharding** [comment]
> and ask rust-bitcoin to also bump to 0.13.

Upcoming `rust-bitcoin v0.31.0` release depends on `hashes v0.13`. Latest `rust-secp256k1` uses a range dependency as shown above.

**Comment by benma** [comment]
@tcharding that seems like a great option. 

> +bitcoin_hashes = { version = ">=0.12.0, <0.13", default-features = false }

Shouldn't that be `<0.14`?

**Comment by jeandudey** [comment]
@benma All of the versions unroll the rounds of sha256, upgrading the crate in a separate minor version is just a convenience for people that want to stick with one version of bitcoin_hashes.

The code is manually unrolled as seen here:

https://docs.rs/bitcoin_hashes/0.13.0/src/bitcoin_hashes/sha256.rs.html#340

We do also use bitcoin_hashes in Passport (specifically for sha256) so it takes a little bit of `.text` space.

That can be disabled by setting the small_hash feature but it's slower.

**Comment by tcharding** [comment]
>> +bitcoin_hashes = { version = ">=0.12.0, <0.13", default-features = false }

> Shouldn't that be <0.14?

My bad, my intention was `<=0.13`, that's what we have in secp. I've not tested with a non-existent version (0.14).

**Comment by tcharding** [comment]
Range dependency works well in secp, AFAIU it should be favoured anytime it works because its more flexible for users. But that is just my understanding, I don't speak for this project.

**Comment by kayabaNerve** [comment]
I opened https://github.com/rust-bitcoin/rust-bip39/pull/60.

**Comment by benma** [comment]
In the meantime I updated my project to bitcoin_hashes 0.13, so I am fine with either 0.13 or the range to include 0.12 as well. The other rust-bitcoin crates also seem to be at 0.13.

**Comment by benma** [comment]
@stevenroose wen release :smile:

**Comment by stevenroose** [comment]
Waiting on https://github.com/rust-bitcoin/rust-bip39/pull/57 and https://github.com/rust-bitcoin/rust-bip39/pull/64. Then will replace this release MR with another one and wait for feedback.

**Comment by stevenroose** [comment]
Sorry for the delay. Merged the other MRs and updated the changelog. Will release when this gets merged.

**Review by tcharding — APPROVED** [review]
ACK 741698655f661c1f08bc36850e469e099369f605

**Comment by tcharding** [comment]
CI fixes in #68 if you want them.

**Review by tcharding — APPROVED** [review]
ACK 125abebde658184e622f21b48678b0453d3a2022

**Comment by benma** [comment]
@stevenroose - everything seems ready for release, but the 2.1.0 tag and release are still missing. Could you publish it? Thanks.

**Comment by benma** [comment]
ping @stevenroose, could you please publish this release?

**Comment by benma** [comment]
another ping @stevenroose. Possibly also look into https://github.com/rust-bitcoin/rust-bip39/issues/37 if there is no time to publish the release after it's been ready for so long.

**Comment by stevenroose** [comment]
Sorry, I haven't been able to keep up with github notifications lately. Published.

**Pull request merged**
