### PR TITLE
Enable 2018 edition, bump MSRV to 1.41 and bump to v2.0.0

### PR DESCRIPTION
**Pull request by stevenroose**
Making a few other MRs obsolete, I think. This will have to wait for the 1.1.0 release first.

### CODE REVIEW

**Comment by stevenroose** [comment]
We might want to add the unicode unpin, but I'm not sure what effect that will have.

**Review by tcharding — APPROVED** [review]
ACK 1b502ce7efeb5fe7b08f3f9675c94ba00b1890fd

**Comment by stevenroose** [comment]
rebased and pushed

**Review by tcharding — APPROVED** [review]
ACK ca7ea1455634828faabd0baaabea7cc78e4ec971

**Comment by stevenroose** [comment]
@tcharding I made some fixes and did the unicode-normalization fix. Could you review the commits (it wouldn't compile in my previous branch and you acked :sweat_smile: ) and could you also double check that it works in v1.41? I don't have rustup available on this machine, so I did some testing using Docker. I think it passes all tests in v1.41 with the rand feature tested.

Normally, using rustup, I used to use this script:
```sh
#!/bin/sh

set -e

MSRV="1.41.0"

CMD="rustup run ${MSRV}"

rm -f Cargo.lock
$CMD cargo generate-lockfile

$CMD cargo build --no-default-features
$CMD cargo test  --no-default-features
$CMD cargo build --no-default-features --features all-languages
$CMD cargo test  --no-default-features --features all-languages
$CMD cargo build --features rand,all-languages
$CMD cargo test  --features rand,all-languages
```

**Comment by stevenroose** [comment]
Let's merge and release the newly merged method in 1.x before merging this.

https://github.com/rust-bitcoin/rust-bip39/pull/44

**Comment by tcharding** [comment]
That script runs, I made one change `MSRV="1.41.1"`, which you had correct everywhere else.

**Review by tcharding — APPROVED** [review]
ACK 40cc51ce2a0a1cf581e45f30bc70eb239d8e069c

**Comment by stevenroose** [comment]
Ok final rebase here after rebasing on v1.2.0 :)

As for 1.41.0/1 I wrote just `1.41` in most places. I did my tests with 1.41.0 and it seems to work.

**Comment by tcharding** [comment]
As you prefer, in `rust-bitcoin` we always say 1.41.1 explicitly and I don't install the 1.41.0 toolchain myself.

**Comment by stevenroose** [comment]
There [don't seem to be a significant difference](https://releases.rs/docs/1.41.1/), but I'll change it to 1.41.1 for consistency.

**Comment by stevenroose** [comment]
@tcharding test run and ack and should be good to go. I'm not happy with Travis disappearing and all my repos being left without CI :/

**Comment by stevenroose** [comment]
Rebased this MR on https://github.com/rust-bitcoin/rust-bip39/pull/45 to add CI, let's see. #45 passes

**Review by tcharding — APPROVED** [review]
ACK f41bf1789dcd684eb081b0115fd2620cda130558

**Pull request merged**
