### PR TITLE
Update the crate to edition 2018

### PR DESCRIPTION
**Pull request by koushiro**
* update to the edition 2018
* update dependencies to the latest
* upgrade the MSRV to 1.36 (required by unicode-normalization 0.1)
* make clippy happy

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by koushiro** [comment]
@stevenroose PTAL

**Comment by stevenroose** [comment]
I'v been doing a series of changes in other PRs that are awaiting review. I'll look at this afterwards and see if I can incorporate some of the things. But I definitely don't want to bump the MSRV above the one of rust-bitcoin, which currently is 1.29.

**Comment by koushiro** [comment]
Why you don't want to bump the MSRV?
The current MSRV is 1.29, which was released in 2018, now it's 2020.
Is there any environment that needs to be compatible with 1.29?

**Comment by stevenroose** [comment]
Well that's something up for rust-bitcoin to decide, feel free to join our IRC channel #rust-bitcoin on Freenode. Especially in an ecosystem like Bitcoin it's not trivial for companies to publicly disclose the Rust version they are using.

**Comment by stevenroose** [comment]
Relevant issue: https://github.com/rust-bitcoin/rust-bitcoin/issues/510

**Pull request closed without merging**
